# Generated by Django 5.2.4 on 2025-07-28 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип')),
                ('recipient', models.CharField(max_length=200, verbose_name='Получатель')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('template_type', models.CharField(choices=[('email_client', 'Email клиенту'), ('email_admin', 'Email администратору'), ('telegram_admin', 'Telegram администратору')], max_length=20, verbose_name='Тип шаблона')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_html', models.BooleanField(default=True, verbose_name='HTML формат')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
    ]
