# Generated by Django 5.2.4 on 2025-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_per_row_desktop', models.IntegerField(default=3, verbose_name='Колонок на десктопе')),
                ('products_per_row_tablet', models.IntegerField(default=2, verbose_name='Колонок на планшете')),
                ('products_per_row_mobile', models.IntegerField(default=1, verbose_name='Колонок на мобильном')),
                ('products_sort_by', models.CharField(choices=[('sort_order', 'Порядок'), ('name', 'Название'), ('created_at', 'Дата создания')], default='sort_order', max_length=20, verbose_name='Сортировать по')),
                ('show_featured_first', models.BooleanField(default=True, verbose_name='Показывать рекомендуемые первыми')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Страница')),
                ('section_name', models.CharField(max_length=100, verbose_name='Секция')),
                ('content_key', models.CharField(max_length=100, verbose_name='Ключ контента')),
                ('content_value', models.TextField(verbose_name='Значение')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('html', 'HTML'), ('number', 'Число'), ('boolean', 'Да/Нет')], max_length=20, verbose_name='Тип')),
            ],
            options={
                'unique_together': {('page_name', 'section_name', 'content_key')},
            },
        ),
    ]
