# Generated by Django 5.2.4 on 2025-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_notified',
            field=models.BooleanField(default=False, verbose_name='Админ уведомлен'),
        ),
        migrations.AddField(
            model_name='application',
            name='client_notified',
            field=models.BooleanField(default=False, verbose_name='Клиент уведомлен'),
        ),
        migrations.AddField(
            model_name='application',
            name='notifications_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомления отправлены'),
        ),
    ]
