# Generated by Django 5.2.4 on 2025-07-28 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('product_type', models.CharField(choices=[('osago', 'ОСАГО'), ('kasko', 'КАСКО'), ('property', 'Недвижимость'), ('accident', 'Несчастный случай'), ('mortgage', 'Ипотека'), ('tick', 'Клещ')], max_length=20, verbose_name='Тип продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('icon', models.CharField(help_text='Название иконки для фронтенда', max_length=50, verbose_name='Иконка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Страховой продукт',
                'verbose_name_plural': 'Страховые продукты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текстовое поле'), ('email', 'Email'), ('phone', 'Телефон'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Выпадающий список'), ('checkbox', 'Чекбокс'), ('textarea', 'Многострочный текст')], max_length=20, verbose_name='Тип поля')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('placeholder', models.CharField(blank=True, max_length=100, verbose_name='Placeholder')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='Правила валидации')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Опции для select')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='products.product')),
            ],
            options={
                'verbose_name': 'Поле продукта',
                'verbose_name_plural': 'Поля продуктов',
                'ordering': ['product', 'sort_order'],
            },
        ),
    ]
