# Generated by Django 5.2.4 on 2025-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list, verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='product',
            name='button_text',
            field=models.CharField(default='Оформить полис', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='product',
            name='card_background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона карточки'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_background_color',
            field=models.CharField(default='#dbeafe', max_length=7, verbose_name='Цвет фона иконки'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Диапазон цен'),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время оформления'),
        ),
    ]
